const AboutPage = () => (
  <div>
    <h1 className="mb-6 text-3xl font-bold text-gray-800">About Chat Genius</h1>

    <h2 className="mb-2 text-2xl font-semibold">Empowering Users with AI</h2>
    <p className="mb-4 text-lg text-gray-700">
      Chat Genius is a web application that leverages the power of OpenAI&apos;s GPT-4 to help users find answers to their questions and get suggestions for
      various tasks. Our mission is to provide an easy-to-use interface, allowing users to access valuable information and insights through GPT-4&apos;s
      advanced AI capabilities.
    </p>
    <h2 className="mb-2 text-2xl font-semibold">Versatile and User-Friendly</h2>
    <p className="mb-4 text-lg text-gray-700">
      Designed for a wide range of applications, Chat Genius assists users in finding the answers they need, whether it&apos;s naming a pet, discovering the
      perfect recipe, or learning a new skill.
    </p>

    <h2 className="mb-2 text-2xl font-semibold">Innovative AI-Powered Development</h2>
    <p className="mb-4 text-lg text-gray-700">
      Throughout the development of Chat Genius, we extensively utilized OpenAI&apos;s ChatGPT to generate a significant portion of our source code. This
      innovative approach accelerated our development process and provided us with practical, high-quality code snippets. By harnessing the power of ChatGPT, we
      efficiently built this helpful tool, delivering an exceptional user experience. Our work demonstrates the immense potential of AI and how it can be
      combined with human ingenuity to create a brighter future together.
    </p>

    <h2 className="mb-2 text-2xl font-semibold">AI-Generated About Content</h2>
    <p className="mb-4 text-lg text-gray-700">
      As a testament to the versatility and usefulness of ChatGPT, even the text content of this About page was generated by the same AI. By leveraging
      ChatGPT&apos;s capabilities, we created informative and engaging content that effectively communicates our goals and vision to our users. This is just one
      example of the countless possibilities that AI can offer in enhancing and simplifying our lives. This text can also be used in README files or other
      documentation to showcase the power of AI-generated content.
    </p>
  </div>
)

export default AboutPage
